package ports

import (
	"context"

	"github.com/IntegraDte/integradte-sdk-go/domain"
)

// IntegraDTEAPI defines the outbound port.
type IntegraDTEAPI interface {
	GetHealth(ctx context.Context) (domain.APIResponse, error)
	Login(ctx context.Context, req domain.LoginRequest) (domain.APIResponse, error)
	CreateFirstBusiness(ctx context.Context, userKey string, req domain.CreateFirstBusinessRequest) (domain.APIResponse, error)
	CreateDocument(ctx context.Context, req domain.CreateDocumentRequest) (domain.APIResponse, error)
	UpdateDocument(ctx context.Context, id string, req domain.UpdateDocumentRequest) (domain.APIResponse, error)
	ListDocuments(ctx context.Context, filter domain.DocumentFilter) (domain.APIResponse, error)
	GetDocument(ctx context.Context, id string) (domain.APIResponse, error)
	GetDocumentStats(ctx context.Context) (domain.APIResponse, error)
	GetDocumentStatsWithFilter(ctx context.Context, filter domain.DocumentFilter) (domain.APIResponse, error)
	CreateCession(ctx context.Context, req domain.CreateCessionRequest) (domain.APIResponse, error)
	RequeueCession(ctx context.Context, req domain.RequeueCessionRequest) (domain.APIResponse, error)
	ListCessions(ctx context.Context, filter domain.CessionFilter) (domain.APIResponse, error)
	GetCession(ctx context.Context, id string) (domain.APIResponse, error)
	GeneratePDF(ctx context.Context, req domain.GeneratePDFRequest, cedible bool) (domain.APIResponse, error)
	CreateBusiness(ctx context.Context, req domain.CreateBusinessRequest) (domain.APIResponse, error)
	ListBusinesses(ctx context.Context) (domain.APIResponse, error)
	GetBusiness(ctx context.Context, id string) (domain.APIResponse, error)
	UpdateBusiness(ctx context.Context, id string, req domain.UpdateBusinessRequest) (domain.APIResponse, error)
	EnableProductionMode(ctx context.Context, req domain.ProductionModeRequest) (domain.APIResponse, error)
	EnableCertificationMode(ctx context.Context) (domain.APIResponse, error)
	UploadCertificate(ctx context.Context, businessID string, req domain.UploadCertificateRequest) (domain.APIResponse, error)
	GetCertificateInfo(ctx context.Context) (domain.APIResponse, error)
	GetMe(ctx context.Context) (domain.APIResponse, error)
	GetBillingBalance(ctx context.Context) (domain.APIResponse, error)
	ListBillingPayments(ctx context.Context, filter domain.PaymentFilter) (domain.APIResponse, error)
	ListBillingCharges(ctx context.Context, filter domain.ChargeFilter) (domain.APIResponse, error)
	ListBillingPlans(ctx context.Context) (domain.APIResponse, error)
	ListBillingInvoices(ctx context.Context, filter domain.InvoiceFilter) (domain.APIResponse, error)
	PreviewSubscriptionUpgrade(ctx context.Context, planID string) (domain.APIResponse, error)
	GetConsumption(ctx context.Context) (domain.APIResponse, error)
	ListConsumptionOverages(ctx context.Context, filter domain.ConsumptionOverageFilter) (domain.APIResponse, error)
	ListConsumptionOperations(ctx context.Context, filter domain.ConsumptionOperationFilter) (domain.APIResponse, error)
	CreatePurchase(ctx context.Context, req domain.CreatePurchaseRequest) (domain.APIResponse, error)
	RequeuePurchase(ctx context.Context, req domain.RequeuePurchaseRequest) (domain.APIResponse, error)
	ListPurchaseAcknowledgments(ctx context.Context, filter domain.PurchaseAcknowledgmentFilter) (domain.APIResponse, error)
	GetNumerationSummary(ctx context.Context) (domain.APIResponse, error)
	GetLastUsedFolio(ctx context.Context, codeSII string) (domain.APIResponse, error)
	ListNumerationRanges(ctx context.Context, filter domain.NumerationRangeFilter) (domain.APIResponse, error)
	UploadNumeration(ctx context.Context, req domain.UploadNumerationRequest) (domain.APIResponse, error)
	DeleteNumeration(ctx context.Context, id string) (domain.APIResponse, error)
	UpdateNumerationNextNumber(ctx context.Context, numerationID string, req domain.UpdateNumerationNextNumberRequest) (domain.APIResponse, error)
	UpdateLowStockConfig(ctx context.Context, req domain.UpdateLowStockConfigRequest) (domain.APIResponse, error)
	RequestNumbers(ctx context.Context, req domain.RequestNumbersRequest) ([]domain.NumberRange, error)
	RequeueDocument(ctx context.Context, req domain.RequeueDocumentRequest) (domain.APIResponse, error)
	RequeueOfflineDocumentStatus(ctx context.Context, req domain.RequeueDocumentRequest) (domain.APIResponse, error)
}
